name: tests
on: [ push, workflow_dispatch ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: install required packages
      run: |
        sudo apt-get install -y iverilog python3 python3-pip
        pip3 install cocotb pytest
        cocotb-config --libpython
        cocotb-config --python-bin
    - name: run tests
      run: |
        cd src
        make
        ! grep failure results.xml

